// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtdtdOgLg0aIZT2LQ2jDuo5PEPuwz410',
    appId: '1:780468138966:web:bce219a7572abf4990ea77',
    messagingSenderId: '780468138966',
    projectId: 'htlmng',
    authDomain: 'htlmng.firebaseapp.com',
    storageBucket: 'htlmng.firebasestorage.app',
    measurementId: 'G-Q4NRF5RGVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSOm2wXHOib7LQzNECCy3Yj54uvfDVrAI',
    appId: '1:780468138966:android:66fcdfb7ef9920c090ea77',
    messagingSenderId: '780468138966',
    projectId: 'htlmng',
    storageBucket: 'htlmng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQz9FN-O3W6PAg0PvBnVwQwEEm6iMDb4Y',
    appId: '1:780468138966:ios:3791fc232b34a3a090ea77',
    messagingSenderId: '780468138966',
    projectId: 'htlmng',
    storageBucket: 'htlmng.firebasestorage.app',
    iosBundleId: 'com.example.hotelmng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQz9FN-O3W6PAg0PvBnVwQwEEm6iMDb4Y',
    appId: '1:780468138966:ios:3791fc232b34a3a090ea77',
    messagingSenderId: '780468138966',
    projectId: 'htlmng',
    storageBucket: 'htlmng.firebasestorage.app',
    iosBundleId: 'com.example.hotelmng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbtdtdOgLg0aIZT2LQ2jDuo5PEPuwz410',
    appId: '1:780468138966:web:e3b9ff10869da84b90ea77',
    messagingSenderId: '780468138966',
    projectId: 'htlmng',
    authDomain: 'htlmng.firebaseapp.com',
    storageBucket: 'htlmng.firebasestorage.app',
    measurementId: 'G-C7P20R9JCP',
  );
}
